remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: NOVA Mental Health Resources
description: A living list of mental health resources for the Northern Virginia area.
show_downloads: false